//! RaxLang v0.1 transpiler to Rust.

use crate::ast::*;

pub struct Transpiler {
    output: String,
    indent: usize,
}

impl Transpiler {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn transpile_program(&mut self, program: &Program) -> String {
        self.emit("// Auto-generated by RaxLang v0.1 transpiler");
        self.emit("// DO NOT EDIT — edit the .rax source file instead");
        self.emit("");
        self.emit("use async_trait::async_trait;");
        self.emit("use raxion_sdk::{AgentMemory, AgentRunner, InferenceRequest, SmartAgent};");
        self.emit("use std::time::Duration;");
        self.emit("");

        let mut agent_name = None;
        for decl in &program.declarations {
            match decl {
                Declaration::Agent(a) => {
                    agent_name = Some(a.name.clone());
                    self.transpile_agent(a);
                }
                Declaration::Fn(f) => self.transpile_fn(f),
            }
        }

        if let Some(name) = agent_name {
            self.emit_main(&name);
        }

        self.output.clone()
    }

    fn transpile_agent(&mut self, agent: &AgentDecl) {
        let struct_name = to_pascal_case(&agent.name);
        let arch = agent.arch.as_deref().unwrap_or("transformer");

        self.emit(&format!("pub struct {} {{", struct_name));
        self.indent += 1;
        self.emit("pub endpoint: String,");
        self.indent -= 1;
        self.emit("}");
        self.emit("");

        self.emit("#[async_trait]");
        self.emit(&format!("impl SmartAgent for {} {{", struct_name));
        self.indent += 1;

        self.emit(&format!(
            "fn name(&self) -> &str {{ \"{}\" }}",
            agent.name
        ));
        self.emit(&format!(
            "fn architecture_type(&self) -> &str {{ \"{}\" }}",
            arch
        ));
        self.emit("");
        self.emit("async fn respond(");
        self.indent += 1;
        self.emit("&self,");
        self.emit("request: &InferenceRequest,");
        self.emit("memory: &AgentMemory,");
        self.indent -= 1;
        self.emit(") -> anyhow::Result<String> {");
        self.indent += 1;

        self.transpile_agent_body(&agent.process_body, &agent.domain);

        self.indent -= 1;
        self.emit("}");

        self.indent -= 1;
        self.emit("}");
        self.emit("");
    }

    fn transpile_agent_body(&mut self, block: &Block, domain: &str) {
        for stmt in &block.statements {
            match stmt {
                Statement::Let { name, value } => {
                    let expr = self.transpile_expr_agent(value);
                    self.emit(&format!("let {} = {};", name, expr));
                }
                Statement::Return(expr) => {
                    let e = self.transpile_expr_agent(expr);
                    self.emit(&format!("Ok({})", e));
                }
                Statement::Expr(expr) => {
                    self.emit(&format!("{};", self.transpile_expr_agent(expr)));
                }
            }
        }
        if block.return_expr.is_none() {
            self.emit(&format!(
                "Ok(format!(\"[{}] processed: {{}}\", &request.query))",
                domain
            ));
        }
    }

    fn transpile_expr_agent(&self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(v) => v.clone(),
            Expr::StringLit(v) => format!("\"{}\".to_string()", v),
            Expr::Call { name, args } => match name.as_str() {
                "recall" => {
                    let top_k = args.get(1).map(|a| self.transpile_expr_agent(a)).unwrap_or_else(|| "3".into());
                    format!("memory.recall(&request.query, {}).await.unwrap_or_default().join(\"\\n\")", top_k)
                }
                "call_model" => {
                    let model = args.first().map(|a| self.transpile_expr_agent(a)).unwrap_or_else(|| "\"llama3.1:8b\".to_string()".into());
                    format!(
                        "{{\n\
                        {i}    let client = reqwest::Client::builder().timeout(Duration::from_secs(30)).build()?;\n\
                        {i}    let body = serde_json::json!({{\n\
                        {i}        \"model\": {model},\n\
                        {i}        \"messages\": [{{\"role\": \"user\", \"content\": &request.query}}],\n\
                        {i}        \"stream\": false\n\
                        {i}    }});\n\
                        {i}    let resp: serde_json::Value = client.post(format!(\"{{}}//api/chat\", self.endpoint))\n\
                        {i}        .json(&body).send().await?.json().await?;\n\
                        {i}    resp[\"message\"][\"content\"].as_str().unwrap_or(\"\").trim().to_string()\n\
                        {i}}}",
                        i = "    ".repeat(self.indent),
                        model = model
                    )
                }
                _ => {
                    let a = args.iter().map(|a| self.transpile_expr_agent(a)).collect::<Vec<_>>().join(", ");
                    format!("{}({})", name, a)
                }
            },
        }
    }

    fn transpile_fn(&mut self, f: &FnDecl) {
        let params = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_type(&p.type_expr)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = f.return_type.as_deref().map(map_type).unwrap_or("()");
        self.emit(&format!("pub fn {}({}) -> {} {{", f.name, params, ret));
        self.indent += 1;
        self.transpile_block(&f.body);
        self.indent -= 1;
        self.emit("}");
    }

    fn transpile_block(&mut self, block: &Block) {
        for stmt in &block.statements {
            match stmt {
                Statement::Let { name, value } => {
                    self.emit(&format!("let {} = {};", name, self.transpile_expr(value)));
                }
                Statement::Return(expr) => {
                    self.emit(&format!("return {};", self.transpile_expr(expr)));
                }
                Statement::Expr(expr) => {
                    self.emit(&format!("{};", self.transpile_expr(expr)));
                }
            }
        }
    }

    fn transpile_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(v) => v.clone(),
            Expr::StringLit(v) => format!("\"{}\".to_string()", v),
            Expr::Call { name, args } => {
                let args = args
                    .iter()
                    .map(|a| self.transpile_expr(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({})", name, args)
            }
        }
    }

    fn emit_main(&mut self, agent_name: &str) {
        let struct_name = to_pascal_case(agent_name);
        self.emit("#[tokio::main]");
        self.emit("async fn main() -> anyhow::Result<()> {");
        self.indent += 1;
        self.emit(&format!("let agent = {} {{", struct_name));
        self.indent += 1;
        self.emit("endpoint: \"http://localhost:11434\".to_owned(),");
        self.indent -= 1;
        self.emit("};");
        self.emit("AgentRunner::new(agent).with_devnet().run().await");
        self.indent -= 1;
        self.emit("}");
    }

    fn emit(&mut self, line: &str) {
        self.output
            .push_str(&format!("{}{}\n", "    ".repeat(self.indent), line));
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn map_type(t: &str) -> &'static str {
    match t {
        "Query" => "&str",
        "Response" => "String",
        "String" => "String",
        _ => "String",
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::parser;

    #[test]
    fn test_pascal_case() {
        assert_eq!(to_pascal_case("math_agent"), "MathAgent");
        assert_eq!(to_pascal_case("code_agent"), "CodeAgent");
    }

    #[test]
    fn test_transpile_generates_smart_agent_impl() {
        let source = r#"
agent test_agent {
    domain: "testing";
    arch: transformer;

    process(query: Query) -> Response {
        let context = recall(query, 3);
        return context;
    }
}
"#;
        let ast = parser::parse(source).expect("parse failed");
        let mut t = Transpiler::new();
        let rust = t.transpile_program(&ast);

        assert!(rust.contains("impl SmartAgent for TestAgent"), "missing SmartAgent impl");
        assert!(rust.contains("fn name(&self)"), "missing name()");
        assert!(rust.contains("fn architecture_type(&self)"), "missing architecture_type()");
        assert!(rust.contains("async fn respond("), "missing respond()");
        assert!(rust.contains("AgentRunner::new(agent)"), "missing main() with AgentRunner");
        assert!(rust.contains("#[tokio::main]"), "missing tokio main");
        assert!(rust.contains("memory.recall("), "recall() not transpiled");
    }

    #[test]
    fn test_transpile_math_agent_rax() {
        let source = r#"
agent math_agent {
    domain: "formal_mathematics";
    arch: neurosymbolic;

    process(query: Query) -> Response {
        let context = recall(query, 3);
        let response = solve_math(query, context);
        return response;
    }
}

fn solve_math(query: Query, context: String) -> Response {
    return call_model("llama3.1:8b", query, context);
}
"#;
        let ast = parser::parse(source).expect("parse failed");
        let mut t = Transpiler::new();
        let rust = t.transpile_program(&ast);

        assert!(rust.contains("struct MathAgent"), "missing struct");
        assert!(rust.contains("neurosymbolic"), "missing arch");
        assert!(rust.contains("async fn main()"), "missing main");
    }
}
