//! RaxLang v0.1 transpiler to Rust.

use crate::ast::*;

pub struct Transpiler {
    output: String,
    indent: usize,
}

impl Transpiler {
    pub fn new() -> Self {
        Self {
            output: String::new(),
            indent: 0,
        }
    }

    pub fn transpile_program(&mut self, program: &Program) -> String {
        self.emit("// Auto-generated by RaxLang v0.1 transpiler");
        self.emit("// DO NOT EDIT — edit the .rax source file instead");
        self.emit("use anyhow::Result;");
        self.emit("");

        for decl in &program.declarations {
            self.transpile_declaration(decl);
        }
        self.output.clone()
    }

    fn transpile_declaration(&mut self, decl: &Declaration) {
        match decl {
            Declaration::Agent(agent) => self.transpile_agent(agent),
            Declaration::Fn(fun) => self.transpile_fn(fun),
        }
    }

    fn transpile_agent(&mut self, agent: &AgentDecl) {
        let name = to_pascal_case(&agent.name);
        self.emit(&format!("pub struct {};", name));
        self.emit(&format!("impl {} {{", name));
        self.indent += 1;
        self.emit(&format!(
            "pub fn domain(&self) -> &'static str {{ \"{}\" }}",
            agent.domain
        ));
        if let Some(arch) = &agent.arch {
            self.emit(&format!(
                "pub fn arch(&self) -> &'static str {{ \"{}\" }}",
                arch
            ));
        }
        self.emit("pub fn process_query(&self, query: &str) -> Result<String> {");
        self.indent += 1;
        self.transpile_block(&agent.process_body);
        self.indent -= 1;
        self.emit("}");
        self.indent -= 1;
        self.emit("}");
        self.emit("");
    }

    fn transpile_fn(&mut self, f: &FnDecl) {
        let params = f
            .params
            .iter()
            .map(|p| format!("{}: {}", p.name, map_type(&p.type_expr)))
            .collect::<Vec<_>>()
            .join(", ");
        let ret = f.return_type.as_deref().map(map_type).unwrap_or("()");
        self.emit(&format!("pub fn {}({}) -> {} {{", f.name, params, ret));
        self.indent += 1;
        self.transpile_block(&f.body);
        self.indent -= 1;
        self.emit("}");
    }

    fn transpile_block(&mut self, block: &Block) {
        for stmt in &block.statements {
            match stmt {
                Statement::Let { name, value } => {
                    self.emit(&format!("let {} = {};", name, self.transpile_expr(value)));
                }
                Statement::Return(expr) => {
                    self.emit(&format!("return {};", self.transpile_expr(expr)));
                }
                Statement::Expr(expr) => {
                    self.emit(&format!("{};", self.transpile_expr(expr)));
                }
            }
        }
        if let Some(expr) = &block.return_expr {
            self.emit(&format!("{}", self.transpile_expr(expr)));
        }
    }

    fn transpile_expr(&self, expr: &Expr) -> String {
        match expr {
            Expr::Ident(v) => v.clone(),
            Expr::StringLit(v) => format!("\"{}\".to_string()", v),
            Expr::Call { name, args } => {
                let args = args
                    .iter()
                    .map(|a| self.transpile_expr(a))
                    .collect::<Vec<_>>()
                    .join(", ");
                format!("{}({})", name, args)
            }
        }
    }

    fn emit(&mut self, line: &str) {
        self.output
            .push_str(&format!("{}{}\n", "    ".repeat(self.indent), line));
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split('_')
        .map(|part| {
            let mut chars = part.chars();
            match chars.next() {
                Some(c) => c.to_ascii_uppercase().to_string() + chars.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn map_type(t: &str) -> &'static str {
    match t {
        "Query" => "&str",
        "Response" => "String",
        "String" => "String",
        _ => "String",
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_pascal_case() {
        assert!(to_pascal_case("math_agent").contains("MathAgent"));
    }
}
